import { useMemo, useState } from 'react';
import type { NotaTransaction } from '../../domain/types';
import { archivePage, workingTransactions } from './nota-workspace-utils';

type Selection = { transactionId: string; pageId: string };

function Drawer({ label, onClose, children }: { label: string; onClose: () => void; children: React.ReactNode }) {
  return <div className="chu-nota-workspace__drawer-backdrop"><aside className="chu-nota-workspace__drawer" role="dialog" aria-modal="true" aria-label={label}><header><h2>{label}</h2><button aria-label={`Tutup ${label}`} onClick={onClose}>×</button></header>{children}</aside></div>;
}

export function WorkingDrawer({ transactions, selected, onClose, onSelect, onAdd, onCancelPage, onCancelTransaction }: {
  transactions: NotaTransaction[]; selected: Selection; onClose: () => void; onSelect: (selection: Selection) => void; onAdd: (transactionId: string) => void; onCancelPage: (selection: Selection) => void; onCancelTransaction: (transactionId: string) => void;
}) {
  const groups = useMemo(() => workingTransactions(transactions).reduce<Record<string, NotaTransaction[]>>((result, transaction) => {
    const key = transaction.customerName.trim() || 'Tanpa pelanggan'; (result[key] ??= []).push(transaction); return result;
  }, {}), [transactions]);
  return <Drawer label="Nota Dikerjakan" onClose={onClose}>{Object.entries(groups).length ? Object.entries(groups).map(([customer, items]) => <section key={customer} className="chu-nota-workspace__drawer-group"><h3>{customer}</h3>{items.map((transaction) => {
    const active = transaction.pages.filter((page) => page.status === 'active');
    return <div key={transaction.id} className="chu-nota-workspace__drawer-transaction"><p><strong>{transaction.baseNumber}</strong><br />{transaction.customerPlace || 'Tanpa tempat'} · {transaction.status === 'reopened' ? 'Dibuka kembali' : 'Draf'}</p><div>{active.map((page) => <button key={page.id} aria-label={`Halaman ${page.suffix}`} aria-pressed={selected.transactionId === transaction.id && selected.pageId === page.id} onClick={() => onSelect({ transactionId: transaction.id, pageId: page.id })}>{page.suffix}</button>)}</div><div><button onClick={() => onAdd(transaction.id)}>Tambah Nota</button><button onClick={() => onCancelTransaction(transaction.id)}>Batalkan transaksi</button>{active.map((page) => <button key={page.id} aria-label={`Batalkan halaman ${page.suffix}`} disabled={active.length < 2} title={active.length < 2 ? 'Minimal satu halaman aktif harus tersisa.' : undefined} onClick={() => onCancelPage({ transactionId: transaction.id, pageId: page.id })}>Batalkan {page.suffix}</button>)}</div>{active.length < 2 && <small>Minimal satu halaman aktif harus tersisa.</small>}</div>;
  })}</section>) : <p className="chu-nota-workspace__empty-message">Tidak ada nota yang sedang dikerjakan.</p>}</Drawer>;
}

export function ListDrawer({ transactions, selected, initialTab = 'archive', onClose, onSelect, onOpenArchive, onRestoreTransaction, onRestorePage }: {
  transactions: NotaTransaction[]; selected: Selection; initialTab?: 'archive' | 'trash'; onClose: () => void; onSelect: (selection: Selection) => void; onOpenArchive: (transactionId: string) => void; onRestoreTransaction: (transactionId: string) => void; onRestorePage: (selection: Selection) => void;
}) {
  const [tab, setTab] = useState<'archive' | 'trash'>(initialTab);
  const [filters, setFilters] = useState({ customer: '', place: '', from: '', to: '' });
  const [page, setPage] = useState(0);
  const archive = archivePage(transactions, filters, page);
  const cancelledPages = transactions.filter((transaction) => transaction.status !== 'cancelled').flatMap((transaction) => transaction.pages.filter((note) => note.status === 'cancelled').map((note) => ({ transaction, note })));
  return <Drawer label="Daftar Nota" onClose={onClose}><div role="tablist" aria-label="Daftar nota"><button role="tab" aria-selected={tab === 'archive'} onClick={() => setTab('archive')}>Arsip</button><button role="tab" aria-selected={tab === 'trash'} onClick={() => setTab('trash')}>Sampah</button></div>{tab === 'archive' ? <><div className="chu-nota-workspace__filters"><input aria-label="Filter pelanggan" value={filters.customer} onChange={(event) => { setFilters({ ...filters, customer: event.target.value }); setPage(0); }} placeholder="Pelanggan" /><input aria-label="Filter tempat" value={filters.place} onChange={(event) => { setFilters({ ...filters, place: event.target.value }); setPage(0); }} placeholder="Tempat" /><input aria-label="Dari tanggal" type="date" value={filters.from} onChange={(event) => { setFilters({ ...filters, from: event.target.value }); setPage(0); }} /><input aria-label="Sampai tanggal" type="date" value={filters.to} onChange={(event) => { setFilters({ ...filters, to: event.target.value }); setPage(0); }} /></div>{archive.items.length ? archive.items.map((transaction) => <div className="chu-nota-workspace__list-item" key={transaction.id}><button onClick={() => onOpenArchive(transaction.id)}>{transaction.baseNumber} · {transaction.customerName || 'Tanpa pelanggan'} · {transaction.customerPlace || 'Tanpa tempat'}</button><button onClick={() => onOpenArchive(transaction.id)}>Buka kembali</button></div>) : <p className="chu-nota-workspace__empty-message">Arsip belum memiliki nota.</p>}<div className="chu-nota-workspace__pagination"><span>{archive.total} nota</span><button disabled={page === 0} onClick={() => setPage(page - 1)}>Sebelumnya</button><span>{page + 1}/{archive.pages}</span><button disabled={page + 1 >= archive.pages} onClick={() => setPage(page + 1)}>Berikutnya</button></div></> : <>{transactions.filter((transaction) => transaction.status === 'cancelled').map((transaction) => <div key={transaction.id} className="chu-nota-workspace__list-item"><span>{transaction.baseNumber} · {transaction.customerName || 'Tanpa pelanggan'}</span><button onClick={() => onRestoreTransaction(transaction.id)}>Pulihkan transaksi</button></div>)}{cancelledPages.map(({ transaction, note }) => <div key={note.id} className="chu-nota-workspace__list-item"><span>{transaction.baseNumber}{note.suffix} · halaman dibatalkan</span><button aria-label={`Pulihkan halaman ${note.suffix}`} onClick={() => { onSelect({ transactionId: transaction.id, pageId: note.id }); onRestorePage({ transactionId: transaction.id, pageId: note.id }); }}>Pulihkan</button></div>)}{!transactions.some((transaction) => transaction.status === 'cancelled') && !cancelledPages.length && <p className="chu-nota-workspace__empty-message">Sampah kosong.</p>}</>}</Drawer>;
}
